//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientSuhu.SRSuhu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRSuhu.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelciusToReamur", ReplyAction="http://tempuri.org/IService1/CelciusToReamurResponse")]
        double CelciusToReamur(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelciusToReamur", ReplyAction="http://tempuri.org/IService1/CelciusToReamurResponse")]
        System.Threading.Tasks.Task<double> CelciusToReamurAsync(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelciusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelciusToFahrenheitResponse")]
        double CelciusToFahrenheit(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelciusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelciusToFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelciusToFahrenheitAsync(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelciusToKelvin", ReplyAction="http://tempuri.org/IService1/CelciusToKelvinResponse")]
        int CelciusToKelvin(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelciusToKelvin", ReplyAction="http://tempuri.org/IService1/CelciusToKelvinResponse")]
        System.Threading.Tasks.Task<int> CelciusToKelvinAsync(int c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebClientSuhu.SRSuhu.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebClientSuhu.SRSuhu.IService1>, WebClientSuhu.SRSuhu.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CelciusToReamur(int c) {
            return base.Channel.CelciusToReamur(c);
        }
        
        public System.Threading.Tasks.Task<double> CelciusToReamurAsync(int c) {
            return base.Channel.CelciusToReamurAsync(c);
        }
        
        public double CelciusToFahrenheit(int c) {
            return base.Channel.CelciusToFahrenheit(c);
        }
        
        public System.Threading.Tasks.Task<double> CelciusToFahrenheitAsync(int c) {
            return base.Channel.CelciusToFahrenheitAsync(c);
        }
        
        public int CelciusToKelvin(int c) {
            return base.Channel.CelciusToKelvin(c);
        }
        
        public System.Threading.Tasks.Task<int> CelciusToKelvinAsync(int c) {
            return base.Channel.CelciusToKelvinAsync(c);
        }
    }
}
